# Generated by Django 3.1.6 on 2021-02-16 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.db_utils


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_auto_20210215_1959'),
        ('users', '0004_user_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=20, verbose_name='地址名称')),
                ('receiver', models.CharField(max_length=20, verbose_name='收货人')),
                ('place', models.CharField(max_length=50, verbose_name='地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机')),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='固定电话')),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='电子邮箱')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('city', utils.db_utils.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='areas.area', verbose_name='市')),
                ('district', utils.db_utils.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='district_addresses', to='areas.area', verbose_name='区')),
                ('province', utils.db_utils.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='areas.area', verbose_name='省')),
                ('user', utils.db_utils.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'md_address',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=utils.db_utils.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.address', verbose_name='默认地址'),
        ),
    ]
