# Generated by Django 3.1.6 on 2021-02-15 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20210215_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID'),
        ),
    ]
